### PR TITLE
Removes reboot that causes ota to never finish.

### PR DESCRIPTION
**Pull request by clearchris**
Removed 2 lines that causes reboots after spiffs update but before flash update.

### CODE REVIEW

**Comment by tobozo** [comment]
hey thanks for your attention :+1: 

Unfortunately the master branch of this fork is too old and missing a few features that were added on the parent repository since it was modified.

I also made a mess of it while trying to synch, sqash and merge my latest changes so it's probably a bad idea to use is as a base as it will bring a lot of garbage in the history :blush:  sorry about that 

If you're still willing to experiment and contribute, please have a look at the [MultiFS](https://github.com/tobozo/esp32FOTA/tree/multiFS) branch instead.

So far the code compiles fine but hasn't been fully tested so it's very likely there are bugs.

**Comment by tobozo** [comment]
hey again ^^ 

I have been able to actually test the code with a [basic example](https://github.com/tobozo/esp32FOTA/blob/multiFS/examples/anyFS/anyFS.ino) and fix a few bugs.

Please let me know if you're still willing to experiment, otherwise feel free to close this pull request.

**Comment by clearchris** [comment]
I have multiFS branch working.  The biggest issue I have seen is that if you run the examples in platformio they don't work because platformio seems to use a non ota partition scheme.  So you may want to include a partitions file in the examples.

If you want to start a thread on testing multifs, there's probably a better spot than here, let me know, I have a few people who will be using this very soon. 

Thanks!

**Comment by tobozo** [comment]
Thanks for your feedback :+1:  

I'm not sure how to reproduce the platformio issue, do you mean the workflow is failing? 

The platformio.ini provided with the library seems a bit outdated but the [tests appear to be working](https://github.com/tobozo/esp32FOTA/actions/runs/3038590568).

I have enabled the discussion tab on this fork and created a [new thread](https://github.com/tobozo/esp32FOTA/discussions/5).

**Pull request closed without merging**
